/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasikeuangan;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File; // Penting: Import kelas File

/**
 *
 * @author Lenovo
 */
public class AplikasiKeuangan extends javax.swing.JFrame {
private DefaultTableModel modelTabel;
private JTable tabelTransaksi;
private TransaksiDAO manajer;


    /**
     * Creates new form AplikasiKeuangan
     */
public AplikasiKeuangan() {
    DatabaseManager.createNewTable();
    // 1. Panggil initComponents() (WAJIB PERTAMA)
    initComponents(); 

    // 2. Inisialisasi komponen yang TIDAK DIBUAT di GUI Builder
    // Gunakan jTable1 (nama dari GUI Builder)
    String[] kolom = {"ID", "Tanggal", "Jenis", "Kategori", "Jumlah", "Deskripsi"};
    modelTabel = new DefaultTableModel(kolom, 0);
    jTable1.setModel(modelTabel);
    
    // Asign jTable1 ke tabelTransaksi agar kode CRUD Anda berfungsi
    tabelTransaksi = jTable1;
    
    // Kita akan menggunakan txtSaldoAkhir sebagai display saldo (sesuai initComponents)
    txtSaldoAkhir.setEditable(false); // Saldo tidak boleh diinput manual

    // 3. Setup Logic
    manajer = new TransaksiDAO();
    tambahAksiListener();
    muatDataAwal();
    perbaruiTampilanTabel();
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tabelTranksaksi = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbJenis = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        jDatetanggal = new com.toedter.calendar.JDateChooser();
        txtJumlah = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSaldoAkhir = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 186, 211));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTranksaksi.setViewportView(jTable1);

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pemasukan", "pengeluaran" }));

        jLabel1.setText("JENIS");

        jLabel2.setText("JUMLAH ");

        jLabel3.setText("DESKRIPSI");

        jLabel4.setText("KATEGORI ");

        jLabel5.setText("TANGGAL");

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gaji", "makanan", "transportasi ", "lain lain" }));

        jDatetanggal.setDate(new java.util.Date());

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 204, 51));
        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTambah.setText("SIMPAN TRANSAKSI");

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasikeuangan/img/compose (1).png"))); // NOI18N

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasikeuangan/img/log-out (1).png"))); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("APLIKASI KEUANGAN ");

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasikeuangan/img/hapus.png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("PRIBADI");

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SALDO AKHIR ");

        txtSaldoAkhir.setBackground(new java.awt.Color(204, 153, 255));
        txtSaldoAkhir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSaldoAkhir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldoAkhir.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSaldoAkhir.setEditable(false); // Pastikan tidak bisa diubah
        txtSaldoAkhir.setText("Rp 0.00");
        txtSaldoAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAkhirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSaldoAkhir)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSaldoAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TRANSAKSI BARU");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("HISTORI TRANSAKSI");

        btnImport.setText("IMPORT");

        btnExport.setText("EXPORT ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeskripsi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel7))
                                    .addComponent(btnTambah)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDatetanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(btnImport)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExport)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tabelTranksaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jDatetanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExport)
                        .addComponent(btnImport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelTranksaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoAkhirActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
char c = evt.getKeyChar();
// Memastikan input adalah digit dan tidak memperbolehkan karakter lain
if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
    evt.consume(); // Menghilangkan input karakter non-digit
}         // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKeyTyped

  private LocalDate convertToLocalDate(Date dateToConvert) {
    if (dateToConvert == null) return null;
    return dateToConvert.toInstant()
      .atZone(ZoneId.systemDefault())
      .toLocalDate();
}  
  private void exportData() {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Data Transaksi (CSV)");
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        String filePath = fileToSave.getAbsolutePath();
        
        // Tambahkan ekstensi .csv jika belum ada
        if (!filePath.toLowerCase().endsWith(".csv")) {
            filePath += ".csv";
        }

        if (manajer.exportToCsv(filePath)) {
            JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke: " + filePath, "Ekspor Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data.", "Ekspor Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
}

private void importData() {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Pilih File Data Transaksi (CSV) untuk Diimpor");
    
    int userSelection = fileChooser.showOpenDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = fileChooser.getSelectedFile();
        String filePath = fileToOpen.getAbsolutePath();
        
        int jumlahDiimpor = manajer.importFromCsv(filePath);
        
        if (jumlahDiimpor > 0) {
            JOptionPane.showMessageDialog(this, jumlahDiimpor + " transaksi berhasil diimpor.", "Impor Sukses", JOptionPane.INFORMATION_MESSAGE);
            perbaruiTampilanTabel(); // Muat ulang tabel untuk menampilkan data baru
        } else if (jumlahDiimpor == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada transaksi yang valid ditemukan dalam file.", "Impor Gagal", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengimpor data.", "Impor Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
}
private void tambahAksiListener() {
    btnTambah.addActionListener(e -> tambahTransaksi());
    btnUbah.addActionListener(e -> ubahTransaksi());
    btnHapus.addActionListener(e -> hapusTransaksi());
    btnExport.addActionListener(e -> exportData());
    btnImport.addActionListener(e -> importData());
    
    // Tombol Keluar
    btnKeluar.addActionListener(e -> keluarAplikasi()); // Menutup aplikasi

    // Aksi klik pada tabel untuk mengisi form saat ingin mengubah/menghapus
    // tabelTransaksi di sini diasumsikan adalah jTable1
    tabelTransaksi.getSelectionModel().addListSelectionListener(e -> {
        // Cek agar event tidak dipanggil berulang kali
        if (!e.getValueIsAdjusting() && tabelTransaksi.getSelectedRow() != -1) {
            tampilkanDataDipilih();
        }
    });
}

    private void keluarAplikasi() {
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin keluar dari aplikasi?", 
        "Konfirmasi Keluar", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih YES, aplikasi akan ditutup
    if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
        System.exit(0);
    } 
    }
    private void tambahTransaksi() {
        try {
            String jenis = cmbJenis.getSelectedItem().toString();
            double jumlah = Double.parseDouble(txtJumlah.getText());
            String kategori = cmbKategori.getSelectedItem().toString();
            String deskripsi = txtDeskripsi.getText();
         // Ambil tanggal dari JDateChooser dan konversi
    Date date = jDatetanggal.getDate();
    if (date == null) throw new IllegalArgumentException("Tanggal tidak boleh kosong.");
    LocalDate tanggal = convertToLocalDate(date);

            Transaksi t = new Transaksi(jenis, jumlah, kategori, deskripsi, tanggal);
            manajer.tambahTransaksi(t);

            JOptionPane.showMessageDialog(this, "Transaksi berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            bersihkanForm();
            perbaruiTampilanTabel();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Format Tanggal salah. Gunakan YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hapusTransaksi() {
        int barisTerpilih = tabelTransaksi.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dihapus dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) modelTabel.getValueAt(barisTerpilih, 0);

        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus transaksi ID " + id + "?", "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            if (manajer.hapusTransaksi(id)) {
                JOptionPane.showMessageDialog(this, "Transaksi berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                perbaruiTampilanTabel();
                bersihkanForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    private void ubahTransaksi() {
        int barisTerpilih = tabelTransaksi.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi dari tabel untuk diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = (int) modelTabel.getValueAt(barisTerpilih, 0);
            String jenis = cmbJenis.getSelectedItem().toString();
            double jumlah = Double.parseDouble(txtJumlah.getText());
            String kategori = cmbKategori.getSelectedItem().toString();
            String deskripsi = txtDeskripsi.getText();
         // Ambil tanggal dari JDateChooser dan konversi
    Date date = jDatetanggal.getDate();
    if (date == null) throw new IllegalArgumentException("Tanggal tidak boleh kosong.");
    LocalDate tanggal = convertToLocalDate(date);
            Transaksi tBaru = new Transaksi(jenis, jumlah, kategori, deskripsi, tanggal);
            
            if (manajer.ubahTransaksi(id, tBaru)) {
                JOptionPane.showMessageDialog(this, "Transaksi ID " + id + " berhasil diubah.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                perbaruiTampilanTabel();
            } else {
                 JOptionPane.showMessageDialog(this, "Gagal mengubah transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan dalam format input.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

private void tampilkanDataDipilih() {
    int barisTerpilih = tabelTransaksi.getSelectedRow();
    
    if (barisTerpilih != -1) {
        // Baris yang dipilih di view
        
        // 1. Ambil data dari Model Tabel
        // Kolom: 0-ID, 1-Tanggal, 2-Jenis, 3-Kategori, 4-Jumlah, 5-Deskripsi
        
        Object jenisObj = modelTabel.getValueAt(barisTerpilih, 2);
        Object kategoriObj = modelTabel.getValueAt(barisTerpilih, 3);
        Object jumlahObj = modelTabel.getValueAt(barisTerpilih, 4);
        Object deskripsiObj = modelTabel.getValueAt(barisTerpilih, 5);
        LocalDate localDate = (LocalDate) modelTabel.getValueAt(barisTerpilih, 1);
        
        // 2. Isi Komponen Input
        
        // ComboBox Jenis
        if (jenisObj != null) {
            cmbJenis.setSelectedItem(jenisObj.toString());
        }
        
        // ComboBox Kategori
        if (kategoriObj != null) {
            cmbKategori.setSelectedItem(kategoriObj.toString());
        }
        
        // TextField Jumlah
        if (jumlahObj != null) {
            txtJumlah.setText(jumlahObj.toString());
        }
        
        // TextField Deskripsi
        if (deskripsiObj != null) {
            txtDeskripsi.setText(deskripsiObj.toString());
        }
        
        // JDateChooser Tanggal (memerlukan konversi)
        if (localDate != null) {
            jDatetanggal.setDate(convertToUtilDate(localDate));
        } else {
            jDatetanggal.setDate(null);
        }
    }
}
    private Date convertToUtilDate(LocalDate localDate) {
    if (localDate == null) return null;
    return Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
}
private void bersihkanForm() {
        txtJumlah.setText("");
        txtDeskripsi.setText("");
        jDatetanggal.setDate(new java.util.Date()); // Set ke tanggal hari ini
        cmbJenis.setSelectedIndex(0);
        cmbKategori.setSelectedIndex(0);
        tabelTransaksi.clearSelection();
        
    }

    private void perbaruiTampilanTabel() {
        // Kosongkan tabel saat ini
        modelTabel.setRowCount(0);

        // Isi ulang dengan data terbaru dari ManajerKeuangan
        for (Transaksi t : manajer.ambilSemuaTransaksi()) {
            Object[] baris = new Object[]{
                t.getId(),
                t.getTanggal(),
                t.getJenis(),
                t.getKategori(),
                t.getJumlah(),
                t.getDeskripsi()
            };
            modelTabel.addRow(baris);
        }
        
        // Perbarui Label Saldo
        double saldo = manajer.hitungSaldoAkhir();

        

    
    // Format output ke String (tanpa HTML color tags karena ini JTextField)
    String saldoText = String.format("Rp %,.2f", saldo);
    
    txtSaldoAkhir.setText(saldoText); 
    
    // Opsi: Beri warna background pada JTextField berdasarkan saldo (Opsional)
    if (saldo >= 0) {
        txtSaldoAkhir.setBackground(new Color(200, 255, 200)); // Hijau Muda
    } else {
        txtSaldoAkhir.setBackground(new Color(255, 200, 200)); // Merah Muda
    }

    }
    
   private void muatDataAwal() {
    // Jika Anda ingin memastikan data awal, jalankan ini HANYA sekali:
     if (manajer.ambilSemuaTransaksi().isEmpty()) {
         manajer.tambahTransaksi(new Transaksi("Pemasukan", 5000000, "Gaji", "Gaji bulanan", LocalDate.now()));
         manajer.tambahTransaksi(new Transaksi("Pengeluaran", 50000, "Makanan", "Makan siang", LocalDate.now()));
     }
    
    // Biarkan kosong agar data diambil dari DB saat aplikasi dibuka.
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbKategori;
    private com.toedter.calendar.JDateChooser jDatetanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tabelTranksaksi;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtSaldoAkhir;
    // End of variables declaration//GEN-END:variables
}
